version: '2'
services:
  openldap:
    image: leejoneshane/openldap
    container_name: openldap
    hostname: ldap
    ports:
      - "389:389"
      - "636:636"
    restart: always
    
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: dbpassword
    ports:
      - "3306:3306"
    restart: always
    
  redis:
    image: redis
    container_name: redis
    restart: always
    
  laravel:
    image: leejoneshane/laravel
    container_name: laravel
    volumes:
      - ./htdocs:/var/www/localhost/htdocs
    environment:
      DOMAIN: ldap.tp.edu.tw
      MAIL: your@gmail.com
      WEB_PASSWORD: password
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: null
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: dbpassword
      LDAP_HOST: ldaps://openldap
      LDAP_ROOTDN: cn=admin,dc=tp,dc=edu,dc=tw
      LDAP_ROOTPWD: test
      MAIL_DRIVER: smtp
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: your@gmail.com
      MAIL_PASSWORD: password
      MAIL_ENCRYPTION: tls
    links:
      - mysql:db
      - redis:cache
      - openldap:openldap
    ports:
      - "80:80"
      - "443:443"
    restart: always
